logging:
  level:
    org.springframework.boot.context.properties: DEBUG

app:
  kafka:
    bootstrap-servers: localhost:9092
    notification:
      topic: notifications-topic
      consumer:
        group-id: notification-group
        concurrency-count: 3

notification-sender:
  server:
    host: localhost
    port: 8090
    scheme: http

spring:
  profiles:
    include:
      - domain